services:
  docs:
    image: quiz_master_local_docs
    container_name: quiz_master_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./quiz_master:/app/quiz_master:z
    ports:
      - '9000:9000'
    command: /start-docs
